apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-ui
  template:
    metadata:
      labels:
        app: registration-ui
    spec:
      containers:
        - name: registration-ui
          image: abeldock/registration-ui:1.0.0-13
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
