apiVersion: v1
kind: Service
metadata:
  name: registration-ui-service
  labels:
    app: registration-ui
spec:
  selector:
    app: registration-ui

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
